import = [
    "~/.config/alacritty/themes/themes/solarized_light.toml"
]

[cursor]
style = { shape = "Block", blinking = "Always" }

[font]
normal = { family = "Lekton Nerd Font", style = "Regular" }
size  = 12.0

[window]
decorations = "Full"
padding = { x = 10, y = 10 }

[keyboard]
bindings = [
    { key = "a", mods = "Command", chars = "\u0002" },
]

[scrolling]
history = 10000
multiplier = 3
